// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJPhS7WlYZpRzjy7ebqvXYTdHD0Kic7s4',
    appId: '1:122853780352:android:42f806bbb999417379af65',
    messagingSenderId: '122853780352',
    projectId: 'sahayak-ai-9519a',
    databaseURL: 'https://sahayak-ai-9519a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sahayak-ai-9519a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTg6yncenhtF4ILuWXGyTLxBtKCie4phk',
    appId: '1:122853780352:ios:2811ce5f4dab84b479af65',
    messagingSenderId: '122853780352',
    projectId: 'sahayak-ai-9519a',
    databaseURL: 'https://sahayak-ai-9519a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sahayak-ai-9519a.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );
}
